// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dto

import (
	"database/sql"
)

type Category struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Post struct {
	ID         int32        `json:"id"`
	UserID     int32        `json:"user_id"`
	CategoryID int32        `json:"category_id"`
	Title      string       `json:"title"`
	Content    string       `json:"content"`
	Image      string       `json:"image"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type User struct {
	ID            int32          `json:"id"`
	Name          string         `json:"name"`
	LastName      string         `json:"last_name"`
	Role          string         `json:"role"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	Description   sql.NullString `json:"description"`
	Image         sql.NullString `json:"image"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	RememberToken sql.NullString `json:"remember_token"`
}
